CREATE TABLE Books(
date	 DATE,
beginningHour	DATE,
DNI VARCHAR(20), 
CONSTRAINT cp_supervises PRIMARY KEY (date, beginningHour, DNI)
CONSTRAINT ca_date_A FOREIGN KEY (date) REFERENCES Availability
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT ca_bhour_A FOREIGN KEY (beginningHour) REFERENCES Availability
ON DELETE CASCADE ON UPDATE CASCADE, 
CONSTRAINT ca_dni_E FOREIGN KEY (DNI) REFERENCES Elderly_People
ON DELETE RESTRICT ON UPDATE CASCADE,
);
