CREATE TABLE Has(
number	 VARCHAR(10),
DNI VARCHAR(20), 
CONSTRAINT cp_has PRIMARY KEY (number,DNI)
CONSTRAINT ca_number_I FOREIGN KEY (number) REFERENCES Invoice
ON DELETE CASCADE ON UPDATE CASCADE, 
CONSTRAINT ca_dni_E FOREIGN KEY (DNI) REFERENCES Elderly_People
ON DELETE RESTRICT ON UPDATE CASCADE,
);
