CREATE TABLE IsAssignedTo(
numberC	 VARCHAR(10),
numberR VARCHAR(20), 
CONSTRAINT cp_IsAssignedTo PRIMARY KEY (numberC,numberR)
CONSTRAINT ca_numberC_C FOREIGN KEY (numberC) REFERENCES Contract
ON DELETE CASCADE ON UPDATE CASCADE, 
CONSTRAINT ca_numberR_R FOREIGN KEY (numberR) REFERENCES Request
ON DELETE RESTRICT ON UPDATE CASCADE,
);
