CREATE TABLE IsPayedBy(
number	 VARCHAR(10),
numberR VARCHAR(20), 
CONSTRAINT cp_IsPayedBy PRIMARY KEY (number,numberR)
CONSTRAINT ca_number_I FOREIGN KEY (number) REFERENCES Invoice
ON DELETE CASCADE ON UPDATE CASCADE, 
CONSTRAINT ca_numberR_R FOREIGN KEY (numberR) REFERENCES Request
ON DELETE RESTRICT ON UPDATE CASCADE,
);
