CREATE TABLE IsPayedBy(
number	 VARCHAR(20),
numberI VARCHAR(20), 
CONSTRAINT cp_IsPayedBy PRIMARY KEY (number,numberI),
CONSTRAINT ca_number_I FOREIGN KEY (numberI) REFERENCES Invoice
ON DELETE CASCADE ON UPDATE CASCADE, 
CONSTRAINT ca_numberR_R FOREIGN KEY (number) REFERENCES Request
ON DELETE RESTRICT ON UPDATE CASCADE
);
