CREATE TABLE Offers(
user	VARCHAR(20)
date	 DATE,
beginningHour	DATE,
CONSTRAINT cp_supervises PRIMARY KEY (date, beginningHour, use)
CONSTRAINT ca_date_A FOREIGN KEY (date) REFERENCES Availability
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT ca_bhour_A FOREIGN KEY (beginningHour) REFERENCES Availability
ON DELETE CASCADE ON UPDATE CASCADE, 
CONSTRAINT ca_user_V FOREIGN KEY (user) REFERENCES Volunteer
ON DELETE RESTRICT ON UPDATE CASCADE,
);
