CREATE TABLE signs(
numberC	 VARCHAR(10),
name VARCHAR(20), 
CONSTRAINT cp_signs PRIMARY KEY (numberC,name)
CONSTRAINT ca_numberC_C FOREIGN KEY (numberC) REFERENCES Contract
ON DELETE CASCADE ON UPDATE CASCADE, 
CONSTRAINT ca_name_C FOREIGN KEY (name) REFERENCES Company
ON DELETE RESTRICT ON UPDATE CASCADE,
);
