CREATE TABLE Supervises(
userCAS	 VARCHAR(10),
DNI VARCHAR(20), 
CONSTRAINT cp_supervises PRIMARY KEY (userCAS,DNI)
CONSTRAINT ca_userCAS_SW FOREIGN KEY (userCAS) REFERENCES SocialWorker
ON DELETE CASCADE ON UPDATE CASCADE, 
CONSTRAINT ca_dni_E FOREIGN KEY (DNI) REFERENCES Elderly_People
ON DELETE RESTRICT ON UPDATE CASCADE,
);
